name: Generate action docs

on:
  - pull_request

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    - uses: bitflight-devops/github-action-readme-generator@v1.0.12
      with:
        # The absolute or relative path to the `action.yml` file to read in from.
        # Default: action.yml
        action: "./deploy-lambda/action.yml"

        # The absolute or relative path to the markdown output file that contains the
        # formatting tokens within it.
        # Default: README.md
        readme: ""

        # The GitHub Action repository owner. i.e: `bitflight-devops`
        owner: "MrAtheist"

        # The GitHub Action repository name. i.e: `github-action-readme-generator`
        repo: "github-action-lambda"

        # Save the provided values in a `.ghadocs.json` file. This will update any
        # existing `.ghdocs.json` file that is in place.
        save: ".ghdocs.json"

        # Use `prettier` to pretty print the new README.md file
        pretty: "true"

        # Enable the update of the usage version to match the latest version in the
        # `package.json` file
        versioning_enabled: ""

        # Set a specific version to display in the README.md
        version_override: ""

        # Prefix the version with this value (if it isn't already prefixed)
        # Default: v
        version_prefix: ""

        # If versioning is disabled show this branch instead
        # Default: main
        versioning_default_branch: "main"

        # Add a prefix to the README title
        # Default: GitHub Action:
        title_prefix: "Github Action: Lambda Deploy"